[context.deploy-preview.environment]
    REACT_APP_API_URL = "https://koinly-staging.herokuapp.com"
    STAGING = "true"
[context.branch-deploy.environment]
    REACT_APP_API_URL = "https://koinly-staging.herokuapp.com"
    STAGING = "true"